EnrollmentApp/EnrollmentApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('student.urls')),
]

EnrollmentApp/student/urls.py
from django.conf.urls import url
from .views import showdata, update, display

app_name = 'dappx'

urlpatterns = [
    url(r'^$', showdata, name='base'),
    url(r'^new/$', update, name='new'),
    url(r'^student/(?P<studentname>\w+)/$', display, name='student'),

]

EnrollmentApp/student/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError


# Create your models here.
class StudentData(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    studentname = models.CharField(max_length=50)
    fathersname = models.CharField(max_length=50)
    dob = models.DateField()
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    pin = models.IntegerField()
    phone = models.CharField(max_length=12, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    classopted = models.IntegerField(validators=[MaxValueValidator(10), MinValueValidator(5)])
    marks = models.IntegerField()
    dateenrolled = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.dob.year < 2010:
            raise ValidationError("The date must be above 2010!")
        super(StudentData, self).save(*args, **kwargs)

EnrollmentApp/student/forms.py
from django import forms
from .models import StudentData

class StudentForm(forms.ModelForm):

    class Meta:
        model = StudentData
        fields = '__all__'

EnrollmentApp/student/views.py
from django.shortcuts import render

from .forms import StudentForm
from .models import StudentData


# Create your views her
# View to list out all the Students data
def showdata(request):
    studentdata = StudentData.objects.all()

    context = {"studentdata": studentdata, }

    return render(request, 'dappx/base.html', context)


# View for enrolling new student
def update(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()

    else:
        # print("else")
        form = StudentForm()

    return render(request, 'dappx/new.html', {'form': form})


# view to display details of particular student
def display(request, studentname):
    data= StudentData.objects.get(studentname=studentname)

    return render(request, 'dappx/student.html', {'data': data})

EnrollmentApp/templates/dappx/Student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Information</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
 <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <!-- Home Page-->
          <li><a class="navbar-brand" href="{% url 'dappx:base' %}">Enrollment App</a></li>
        </div>
</nav>
<div class="container theme-showcase margin-top-navbar" role="main" style="margin-top: 50px">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-sm">
    {% if data is not None %}
      <!-- student detail information-->
                <tr><td>Sno:</td><td>{{ data.id }}</td></tr>
                <tr><td>Student Name:</td><td>{{ data.studentname }}</td></tr>
                <tr><td>Father's Name:</td><td>{{ data.fathersname }}</td></tr>
                <tr><td>Dob:</td><td>{{ data.dob }}</td></tr>
                <tr><td>Address:</td><td>{{ data.address }}</td></tr>
                <tr><td>City:</td><td>{{ data.city }}</td></tr>
                <tr><td>State:</td><td>{{ data.state }}</td></tr>
                <tr><td>Pin:</td><td>{{ data.pin }}</td></tr>
                <tr><td>Phone:</td><td>{{ data.phone }}</td></tr>
                <tr><td>Email:</td><td>{{ data.email }}</td></tr>
                <tr><td>Class:</td><td>{{ data.classopted }}</td></tr>
                <tr><td>Marks %:</td><td>{{ data.marks }}</td></tr>
                <tr><td>Date Enrolled:</td><td>{{ data.dateenrolled }}</td></tr>
    {% else %}
        <tr>
            <td>No student data returned.</td>
        </tr>
    {% endif %}
            </table>
            </div>
        </div>
    </div>

</body>
</html>

EnrollmentApp/templates/dappx/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML Table Pagination Example</title>

    <meta name="author" content="FrontendScript" />
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <style type="text/css">
            table{
                background: #fff;
            }
        .paging-nav {
          text-align: right;
          padding-top: 2px;
        }

        .paging-nav a {
          margin: auto 1px;
          text-decoration: none;
          display: inline-block;
          padding: 1px 7px;
          background: #91b9e6;
          color: white;
          border-radius: 3px;
        }

        .paging-nav .selected-page {
          background: #187ed5;
          font-weight: bold;
        }

        .paging-nav,
        #tableData {
          width: 400px;
          margin: 0 auto;
          font-family: Arial, sans-serif;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <!-- Home Page-->
          <li><a class="navbar-brand" href="{% url 'dappx:base' %}">Enrollment App</a></li>

      </div>
    </nav>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
<!--          New Student Enrollment Page-->
          <a class="navbar-brand" style="float: right;" href="{% url 'dappx:new' %}">New Student</a>
      </div>
    </nav>


<section>
    <div class="rt-container">
          <div class="col-rt-12">
              <div class="Scriptcontent">
                <table id="tableData" class="table table-striped table-bordered table-sm" width="200%" >
                    <thead>
                    <tr>
                    <td><b>SNo</b></td>
                    <td ><b>Student Name</b></td>
                    <td><b>Email</b></td>
                    <td><b>Phone#</b></td>
                    <td><b>Class</b></td>
                    <td><b>Marks%</b></td>
                    </tr>
                    </thead>

                    {% for data in studentdata %}
                    <tbody>
                    <tr>
                    <td>{{ data.id }}</td>
                    <td><a href="{% url 'dappx:student' studentname=data.studentname %}">{{ data.studentname }}</a></td>
                    <td>{{ data.email }}</td>
                    <td>{{ data.phone }}</td>
                    <td>{{ data.classopted }}</td>
                    <td>{{ data.marks }}</td>
                    </tr>
                    </tbody>
                        {% endfor %}
                </table>
              </div>
		</div>
    </div>
</section>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
     <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<!--    pagination-->
     <script>(function($) {
            $(function() {
                $.widget("zpd.paging", {
                    options: {
                        limit: 5,
                        rowDisplayStyle: 'block',
                        activePage: 0,
                        rows: []
                    },
                    _create: function() {
                        var rows = $("tbody", this.element).children();
                        this.options.rows = rows;
                        this.options.rowDisplayStyle = rows.css('display');
                        var nav = this._getNavBar();
                        this.element.after(nav);
                        this.showPage(0);
                    },
                    _getNavBar: function() {
                        var rows = this.options.rows;
                        var nav = $('<div>', {class: 'paging-nav'});
                        for (var i = 0; i < Math.ceil(rows.length / this.options.limit); i++) {
                            this._on($('<a>', {
                                href: '#',
                                text: (i + 1),
                                "data-page": (i)
                            }).appendTo(nav),
                                    {click: "pageClickHandler"});
                        }
                        //create previous link
                        this._on($('<a>', {
                            href: '#',
                            text: '<<',
                            "data-direction": -1
                        }).prependTo(nav),
                                {click: "pageStepHandler"});
                        //create next link
                        this._on($('<a>', {
                            href: '#',
                            text: '>>',
                            "data-direction": +1
                        }).appendTo(nav),
                                {click: "pageStepHandler"});
                        return nav;
                    },
                    showPage: function(pageNum) {
                        var num = pageNum * 1; //it has to be numeric
                        this.options.activePage = num;
                        var rows = this.options.rows;
                        var limit = this.options.limit;
                        for (var i = 0; i < rows.length; i++) {
                            if (i >= limit * num && i < limit * (num + 1)) {
                                $(rows[i]).css('display', this.options.rowDisplayStyle);
                            } else {
                                $(rows[i]).css('display', 'none');
                            }
                        }
                    },
                    pageClickHandler: function(event) {
                        event.preventDefault();
                        $(event.target).siblings().attr('class', "");
                        $(event.target).attr('class', "selected-page");
                        var pageNum = $(event.target).attr('data-page');
                        this.showPage(pageNum);
                    },
                    pageStepHandler: function(event) {
                        event.preventDefault();
                        //get the direction and ensure it's numeric
                        var dir = $(event.target).attr('data-direction') * 1;
                        var pageNum = this.options.activePage + dir;
                        //if we're in limit, trigger the requested pages link
                        if (pageNum >= 0 && pageNum < this.options.rows.length) {
                            $("a[data-page=" + pageNum + "]", $(event.target).parent()).click();
                        }
                    }
                });
            });
        })(jQuery);
        </script>
<!--    pagination limited to 8 entities-->
        <script type="text/javascript">
            $(document).ready(function() {
                $('#tableData').paging({limit:8});
            });
        </script>


</body>
</html>

EnrollmentApp/templates/dappx/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Student</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
<!--        Home Page-->
          <li><a class="navbar-brand" href="{% url 'dappx:base' %}">Enrollment App</a></li>
      </div>
    </nav>

<!--    New Student Enrollment Form-->
        <div class="container">
            <form method="POST">
                <fieldset>
                 <legend>New Student</legend>
                     {% csrf_token %}
                    {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
                </fieldset>
            </form>
        </div>

</body>
</html>